// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgpszvgsjgkuctcjwwgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBncHN6dmdzamdrdWN0Y2p3d2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjI3NzgsImV4cCI6MjA3MDg5ODc3OH0.NZ3n4rRBsTEuNet65ji8Bl1GFwS-Gvek2ZMRPYFgl5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});