name: Android CI - Debug APK & AAB

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: ['perf/**', 'feat/**', 'fix/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web assets
        run: npm run build

      - name: Add Android platform
        run: npx cap add android

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Gradle Wrapper Verification
        run: cd android && ./gradlew wrapper --gradle-version

      - name: Android Lint (optional, non-blocking)
        run: cd android && ./gradlew lintVitalDebug || true

      - name: Assemble Debug APK
        run: cd android && ./gradlew :app:assembleDebug

      - name: Build Debug AAB
        run: cd android && ./gradlew :app:bundleDebug

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-builds
          path: |
            android/app/build/outputs/apk/debug/*.apk
            android/app/build/outputs/bundle/debug/*.aab
          retention-days: 30

      - name: Job Summary
        run: |
          echo "### Android CI Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "- APK: android/app/build/outputs/apk/debug/app-debug.apk" >> $GITHUB_STEP_SUMMARY
          echo "- AAB: android/app/build/outputs/bundle/debug/app-debug.aab" >> $GITHUB_STEP_SUMMARY