name: Android Debug Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for git SHA in build info
    
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        cmake: 3.22.1
        ndk: 25.2.9519653
    
    - name: Accept Android SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build web assets
      env:
        BUILD_TARGET: native
      run: npm run build
    
    - name: Add Android platform
      run: npx cap add android || echo "Android platform already exists"
    
    - name: Sync Capacitor
      run: npx cap sync android
    
    - name: Verify local configuration
      run: npm run verify:local
    
    - name: Make gradlew executable
      run: chmod +x ./android/gradlew
    
    - name: Build Android Debug APK
      working-directory: ./android
      run: ./gradlew assembleDebug --no-daemon --stacktrace
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
    
    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          android/app/build/reports/
          android/app/build/tmp/
        retention-days: 7