name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install --frozen-lockfile

    - name: Type check
      run: npm run typecheck

    - name: Lint
      run: npm run lint

    - name: Unit tests with coverage
      run: npm run coverage

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Build application
      run: npm run build

    - name: Start preview server and run E2E tests
      run: |
        npm run preview &
        sleep 5
        npm run e2e

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: coverage/

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload test traces
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-traces
        path: test-results/
        retention-days: 30

  coverage-check:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install --frozen-lockfile

    - name: Run coverage with enforcement
      run: |
        npm run coverage
        echo "Coverage thresholds enforced: lines=35%, branches=30%, functions=35%, statements=35%"

    - name: Generate coverage summary
      run: |
        if [ -f coverage/coverage-summary.json ]; then
          echo "Coverage Summary:"
          cat coverage/coverage-summary.json | jq '.total'
        fi