name: CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint
        continue-on-error: false

      - name: Typecheck (optional)
        run: npm run typecheck --if-present

      - name: Test (optional)
        run: npm test --if-present

      - name: Save ESLint report
        if: always()
        run: npm run lint:report || true
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-reports
          path: reports
      - name: Audit (report only)
        if: always()
        run: npm audit --production --json > reports/npm-audit-after.json || true
      - name: Upload audit & outdated
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: deps-audit-and-outdated
          path: reports
