name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build (optional)
        run: npm run build --if-present

      - name: Determine changed files
        run: |
          git fetch origin main --depth=1 || true
          BASE=$(git merge-base HEAD origin/main || echo "")
          if [ -n "$BASE" ]; then
            git diff --name-only "$BASE"...HEAD > changed_all.txt
          else
            git diff --name-only HEAD~1 > changed_all.txt
          fi
          grep -E '\.(ts|tsx|js|jsx)$' changed_all.txt > changed_lint.txt || true
          echo "Changed files:" && cat changed_lint.txt || true

      - name: Lint (changed files)
        run: |
          if [ ! -s changed_lint.txt ]; then
            echo "No lintable file changes in this PR."; exit 0; fi
          npx eslint --max-warnings=0 $(cat changed_lint.txt)

      - name: Full Lint (report-only)
        if: always()
        run: |
          mkdir -p reports
          npx eslint -f json -o reports/eslint.json . || true

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-reports
          path: reports
