name: Feature Flags Validation

on:
  pull_request:
    paths:
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
      - 'src/flags/**'
      - 'scripts/validate-flags.cjs'
  push:
    branches: [main]
    paths:
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
      - 'src/flags/**'
      - 'scripts/validate-flags.cjs'

jobs:
  validate-flags:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate feature flags
      run: node scripts/validate-flags.cjs
    
    - name: Report validation status
      if: failure()
      run: |
        echo "::error::Feature flags validation failed!"
        echo "Please check:"
        echo "- All flags used in code exist in FLAG_REGISTRY"
        echo "- No dangerous content in flag descriptions"
        echo "- Consider removing unused flags from registry"