name: GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  github-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build web
        run: npm run build

      - name: Add Android platform and sync
        run: |
          npx cap add android
          npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build signed release AAB
        run: |
          cd android
          ./gradlew :app:bundleRelease

      - name: Generate release notes
        id: notes
        run: |
          NOTES=$(npm run -s release:notes)
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.notes.outputs.notes }}
          draft: false
          prerelease: false
          files: |
            android/app/build/outputs/bundle/release/app-release.aab
            android/app/build/outputs/mapping/release/mapping.txt

      - name: Job Summary
        run: |
          echo "## Release Artifacts Created" >> $GITHUB_STEP_SUMMARY
          echo "- **AAB**: android/app/build/outputs/bundle/release/app-release.aab" >> $GITHUB_STEP_SUMMARY
          echo "- **ProGuard mapping**: android/app/build/outputs/mapping/release/mapping.txt" >> $GITHUB_STEP_SUMMARY
          echo "- **Release notes length**: $(echo '${{ steps.notes.outputs.notes }}' | wc -c) characters" >> $GITHUB_STEP_SUMMARY

      - name: Clean up keystore (if any)
        run: |
          rm -f android/app/keystore.jks || true
          rm -f android/keystore.jks || true