name: Security Audit

on:
  # Weekly scheduled run
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM UTC
  
  # Run on PRs that affect dependencies
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  security-audit:
    name: NPM Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        id: audit
        run: |
          echo "Running npm audit with high/critical threshold..."
          npm audit --audit-level=high --json > audit-results.json || echo "audit_failed=true" >> $GITHUB_OUTPUT
          
          # Generate summary table
          echo "## Security Audit Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Severity | Count |" >> $GITHUB_STEP_SUMMARY  
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          
          # Parse audit results and create summary
          if [ -f audit-results.json ]; then
            CRITICAL=$(cat audit-results.json | jq -r '.vulnerabilities | to_entries[] | select(.value.severity == "critical") | .key' | wc -l)
            HIGH=$(cat audit-results.json | jq -r '.vulnerabilities | to_entries[] | select(.value.severity == "high") | .key' | wc -l)
            MODERATE=$(cat audit-results.json | jq -r '.vulnerabilities | to_entries[] | select(.value.severity == "moderate") | .key' | wc -l)
            LOW=$(cat audit-results.json | jq -r '.vulnerabilities | to_entries[] | select(.value.severity == "low") | .key' | wc -l)
            
            echo "| Critical | $CRITICAL |" >> $GITHUB_STEP_SUMMARY
            echo "| High | $HIGH |" >> $GITHUB_STEP_SUMMARY
            echo "| Moderate | $MODERATE |" >> $GITHUB_STEP_SUMMARY
            echo "| Low | $LOW |" >> $GITHUB_STEP_SUMMARY
            
            # Print detailed audit output
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Detailed Audit Results" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            npm audit >> $GITHUB_STEP_SUMMARY || true
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload audit results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-audit-results-${{ github.run_number }}
          path: audit-results.json
          retention-days: 30

      - name: Fail on high/critical vulnerabilities
        if: steps.audit.outputs.audit_failed == 'true'
        run: |
          echo "❌ Security audit failed due to high or critical vulnerabilities"
          exit 1